apiVersion: v1
kind: Namespace
metadata:
  labels:
    kiali.io/member-of: istio-system
    kubernetes.io/metadata.name: istio-system
    maistra.io/ignore-namespace: ignore
    maistra.io/member-of: istio-system
  name: istio-system
spec:
  finalizers:
    - kubernetes
